server:
  port: 8080

spring:
  application:
    name: customer
  #    database
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://postgres:5432/customer
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

  rabbitmq:
    addresses: rabbitmq:5672

#eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

# tracing

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans




# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

rabbitmq:
  exchanges:
    internal: internal.exchanges
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-keys