server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://localhost:5432/customer
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
