server:
  port: 8083
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      enabled: true

# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

